site_name: Alice
repo_url: https://github.com/Zinglish/alice
theme: readthedocs

pages:
- ['index.md', 'Introduction']

- ['plugins/index.md', 'Plugins', 'Vanilla Plugins']
- ['plugins/installing.md', 'Plugins', 'Installing a plugin']
- ['plugins/priorities.md', 'Plugins', 'Priorities']

- ['developing-plugins/index.md', 'Developing Plugins', 'Plugins: a developers guide']